Repository berty/www.berty.tech, pull requests merged in 2020-08, with the labels that each got.

#131 feat(blog): create blogpost about how to create a strong password
  bertytech/content/blog/create-strong-password/create-strong-password.jpg
  bertytech/content/blog/create-strong-password/index.md
Labels: enhancement, ✅ Approved

#133 feat: create nl42
  bertytech/content/newsletter/news-42/index.md
Labels: enhancement, ✅ Approved

#136 fix: app-site-association
  bertytech/static/apple-app-site-association
Labels: bug, 🔍 Ready for Review

#132 feat(blog): create blogpost about password manager
  bertytech/content/blog/best-password-manager/index.md
  bertytech/content/blog/best-password-manager/password-manager.jpg
Labels: enhancement, ✅ Approved

#135 fix: homepage bg line
  bertytech/assets/css/style.scss
Labels: bug, 🔍 Ready for Review

#137 feat(blog): create blogpost about metadata in mobile messaging
  bertytech/content/blog/metadata-mobile-messaging/index.md
  bertytech/content/blog/metadata-mobile-messaging/metadata-mobile-messaging.jpg
Labels: enhancement, 🔍 Ready for Review

#140 feat(blog): create new blogpost about sim swapping
  bertytech/content/blog/sim-swapping/index.md
  bertytech/content/blog/sim-swapping/sim-swapping.png
Labels: enhancement, ✅ Approved
