Repository berty/www.berty.tech, pull requests merged in 2020-10, with the labels that each got.

#158 feat: create news46
  bertytech/content/newsletter/news-46/index.md
Labels: enhancement, 🔍 Ready for Review

#159 feat: create nl47
  bertytech/content/newsletter/news-47/index.md
Labels: enhancement, 🔍 Ready for Review

#160 Support i18n
  bertytech/config.yaml
  bertytech/content/about/index.md
  bertytech/content/compare-table-apps/index.md
  bertytech/i18n/en.yaml
  bertytech/layouts/_default/about.html
  bertytech/layouts/blog/single.html
  bertytech/layouts/challenges/list.html
  bertytech/layouts/docs/list.html
  bertytech/layouts/docs/single.html
  bertytech/layouts/newsletter/list.html
  bertytech/layouts/newsletter/single.html
  bertytech/layouts/partials/block_action_contact_us.html
  bertytech/layouts/partials/block_action_go_to_github.html
  bertytech/layouts/partials/block_action_read_docs.html
  bertytech/layouts/partials/block_action_read_faq.html
  bertytech/layouts/partials/block_action_request_talk.html
  bertytech/layouts/partials/btn_support_our_work.html
  bertytech/layouts/partials/compare-messenger-apps.html
  bertytech/layouts/partials/docs_card_m.html
  bertytech/layouts/partials/docs_card_s.html
  bertytech/layouts/partials/head.html
  bertytech/layouts/partials/page_title.html
  bertytech/layouts/partials/post_card.html
  bertytech/layouts/partials/post_footer.html
  bertytech/layouts/partials/section_newsletter.html
  bertytech/layouts/partials/tag_card.html
  bertytech/layouts/shortcodes/display_directory_images.html
  bertytech/layouts/shortcodes/display_section_about.html
  bertytech/layouts/shortcodes/display_section_press.html
  crowdin.yml
Labels: 🔍 Ready for Review

#164 chore: add badges
  README.md
Labels: chore, 🔍 Ready for Review

#165 Change i18n to TOML format
  bertytech/i18n/en.toml
  bertytech/i18n/en.yaml
  bertytech/i18n/fr.toml
  bertytech/ignore-build.sh
  bertytech/netlify.toml
  crowdin.yml
Labels: ✅ Approved

#166 fix: New Crowdin updates (French)
  bertytech/config.yaml
  bertytech/content/_index.fr.md
  bertytech/content/about/index.fr.md
  bertytech/content/blog/berty-at-fosdem-2020/index.fr.md
  bertytech/content/easteregg.fr.md
  bertytech/content/faq/_index.fr.md
  bertytech/content/features/index.fr.md
  bertytech/content/help/_index.fr.md
Labels: bug, 🔍 Ready for Review

#168 Improve i18n
  bertytech/config.yaml
  bertytech/content/blog/2FA/index.fr.md
  bertytech/layouts/blog/single.html
  bertytech/layouts/partials/footer.html
  bertytech/layouts/partials/head.html
  bertytech/layouts/partials/navbar.html
  bertytech/layouts/partials/rich-snippets/article-inner.html
  bertytech/layouts/partials/rich-snippets/webpage-inner.html
Labels: ✅ Approved

#172 feat: create a blogpost about closed release beta
  bertytech/content/blog/closed-beta-berty/2020-09-28-Berty-Blogpost-Release-closed-Beta.png
  bertytech/content/blog/closed-beta-berty/index.md
Labels: enhancement, ✅ Approved

#171 Update title
  bertytech/content/blog/2FA/index.md
Labels: ✅ Approved

#173 feat: create news-48
  bertytech/content/newsletter/news-48/index.md
Labels: enhancement, 🔍 Ready for Review

#177 Crowdin fixes
  bertytech/content/faq/10-Will the app hide ip addresses and metadata/index.md
  bertytech/content/faq/11-What's the encryption protocol used in Berty/index.md
  bertytech/content/faq/12-Will Berty be free/index.md
  bertytech/content/faq/13-Will Berty have features such as self-destructing messages and BOR/index.md
  bertytech/content/faq/14-Will it have file sharing, voice-& video chat/index.md
  bertytech/layouts/partials/discourse_comments.html
  bertytech/layouts/partials/head.html
  bertytech/scripts/sanitize-filenames.js
Labels: ✅ Approved
