Repository berty/www.berty.tech, pull requests merged in 2020-09, with the labels that each got.

#143 docs: Change Hugo to Hugo Extended in README.md
  README.md
Labels: documentation, ✅ Approved

#144 feat: news 44
  bertytech/content/newsletter/news-44/index.md
Labels: enhancement, 🔍 Ready for Review

#141 chore: Removing useless execution bits.
  bertytech/assets/css/slick.scss
Labels: chore, ✅ Approved

#147 Feat/ipfs deploy
  AUTHORS
  bertyart/Makefile
  bertyart/post-build.sh
Labels: ✅ Approved

#146 feat: Adding go-tor-transport to projects.
  bertytech/assets/css/style.scss
  bertytech/content/docs/assets/index.md
  bertytech/content/docs/go-tor-transport/index.md
  bertytech/content/docs/yolo/index.md
Labels: enhancement, ✅ Approved

#148 feat: configure vanity URL for go-tor-transport
  bertytech/go-get.csv
Labels: enhancement, 🔍 Ready for Review

#149 fix: use new repo name for go-libp2p-tor-transport
  bertytech/go-get.csv
Labels: bug, 🔍 Ready for Review

#150 Fix relative urls
  bertytech/layouts/blog/single.html
  bertytech/layouts/fakepost/single.html
  bertytech/layouts/faq/list.html
  bertytech/layouts/jobs/single.html
  bertytech/layouts/partials/block_action_request_talk.html
  bertytech/layouts/partials/block_action_suggest_question.html
  bertytech/layouts/partials/footer_menu.html
  bertytech/layouts/partials/head.html
  bertytech/layouts/partials/navbar.html
  bertytech/layouts/partials/navbar_old.html
  bertytech/layouts/shortcodes/display_directory_images.html
  bertytech/layouts/shortcodes/display_section_contact_secure.html
  bertytech/layouts/shortcodes/display_section_press.html
  bertytech/layouts/shortcodes/display_section_social.html
  bertytech/layouts/shortcodes/img.html
  bertytech/layouts/shortcodes/obscure.html
Labels: 🔍 Ready for Review

#151 fix: absolute amp-script paths
  bertytech/layouts/faq/list.html
  bertytech/layouts/jobs/single.html
  bertytech/layouts/partials/block_action_request_talk.html
  bertytech/layouts/partials/block_action_suggest_question.html
  bertytech/layouts/partials/navbar.html
  bertytech/layouts/shortcodes/display_section_contact_secure.html
  bertytech/layouts/shortcodes/display_section_press.html
  bertytech/layouts/shortcodes/display_section_social.html
  bertytech/layouts/shortcodes/obscure.html
Labels: bug, 🔍 Ready for Review

#153 Make home lottie animation relative
  bertytech/layouts/index.html
Labels: ✅ Approved

#154 Added go-libtor to the go-get.csv.
  bertytech/go-get.csv
Labels: ✅ Approved

#157 feat: create nl45
  bertytech/content/newsletter/news-45/index.md
Labels: enhancement, ✨ Merged

#156 feat(blog): create blogpost about 2FA
  bertytech/content/blog/2FA/2020-08-31-Berty-Blogpost-2FA.jpg
  bertytech/content/blog/2FA/index.md
Labels: enhancement, ✅ Approved
