Repository berty/www.berty.tech, pull requests merged in 2020-12, with the labels that each got.

#206 feat: create watching3
  bertytech/content/blog/surveillance-france/2020-11-30-Berty-Blogpost-Watching-global-security-and-surveillance-in-france_copie.png
  bertytech/content/blog/surveillance-france/index.md
Labels: enhancement, ✅ Approved, 🔍 Ready for Review

#207 feat: create initial draft of translation blogpost
  bertytech/content/blog/berty-translation/2020-04-12-Berty-BlogPost-translate-Berty.png
  bertytech/content/blog/berty-translation/index.md
  bertytech/content/faq/1-advantages/index.md
  bertytech/package-lock.json
Labels: enhancement, ✅ Approved

#208 Add href alternate tags
  bertytech/config.yaml
  bertytech/layouts/partials/head.html
Labels: ✅ Approved

#211 feat: create blogpost about 2020 talks
  bertytech/content/blog/2020-talks/2020-14-12-Berty-BlogPost-TALKS_AT_PBWS_&_IPFS_WRAP_UP_2020.jpg
  bertytech/content/blog/2020-talks/index.md
Labels: enhancement, ✅ Approved

#215 New Crowdin updates
  bertytech/content/blog/2020-talks/index.fr.md
  bertytech/content/blog/2020-talks/index.id-id.md
Labels: ✅ Approved

#216 feat: support encrypted link's name
  bertytech/assets/js/main.js
Labels: enhancement, 🔍 Ready for Review

#218 feat: create nl51
  bertytech/content/newsletter/news-51/index.md
Labels: enhancement
