Repository berty/www.berty.tech, pull requests merged in 2020-11, with the labels that each got.

#179 Move frontmatter to first line
  bertytech/content/blog/future-of-berty/index.md
Labels: ✅ Approved

#182 fix docs link in footer
  bertytech/layouts/partials/footer.html
Labels: ✅ Approved

#183 Improve translation comparison
  bertytech/layouts/partials/head.html
Labels: ✅ Approved

#185 include compare-table-apps
  crowdin.yml
Labels: ✅ Approved

#186 New translations index.md (French)
  bertytech/content/newsletter/news-13/index.fr.md
Labels: 🔍 Ready for Review

#188 Auto add translations script
  bertytech/package-lock.json
  bertytech/package.json
  bertytech/pre-build.sh
  bertytech/scripts/create-translation-files.js
  bertytech/scripts/package-lock.json
  bertytech/scripts/package.json
Labels: ✅ Approved

#187 chore: new i18n updates
  bertytech/content/compare-table-apps/berty.fr.md
  bertytech/content/compare-table-apps/facebook.fr.md
  bertytech/content/compare-table-apps/firechat.fr.md
  bertytech/content/compare-table-apps/imessage.fr.md
  bertytech/content/compare-table-apps/index.fr.md
  bertytech/content/compare-table-apps/jami.fr.md
  bertytech/content/compare-table-apps/matrix.fr.md
  bertytech/content/compare-table-apps/olvid.fr.md
  bertytech/content/compare-table-apps/session.fr.md
  bertytech/content/compare-table-apps/signal.fr.md
  bertytech/content/compare-table-apps/skred.fr.md
  bertytech/content/compare-table-apps/skuttlebut.fr.md
  bertytech/content/compare-table-apps/telegram.fr.md
  bertytech/content/compare-table-apps/threema.fr.md
  bertytech/content/compare-table-apps/wechat.fr.md
  bertytech/content/compare-table-apps/whatsapp.fr.md
Labels: chore, 🔍 Ready for Review

#190 feat: create Art4Privacy#1 blogpost
  bertytech/content/blog/art-for-privacy/Djalouz-Art4Privacy1.png
  bertytech/content/blog/art-for-privacy/index.md
Labels: enhancement, 🔍 Ready for Review

#191 feat: create blog post about cybersecurity
  bertytech/content/blog/Cybersecurity-Fundamentals/cybersecurity.jpg
  bertytech/content/blog/Cybersecurity-Fundamentals/index.md
Labels: enhancement, 🔍 Ready for Review

#189 feat: i18n updates
  bertytech/content/blog/2FA/index.fr.md
  bertytech/content/blog/Cybersecurity-Fundamentals/index.fr.md
  bertytech/content/blog/art-for-privacy/index.fr.md
  bertytech/content/blog/berty-at-nantes-p2p/index.fr.md
  bertytech/content/blog/bluetooth-low-energy/index.fr.md
  bertytech/content/blog/closed-beta-berty/index.fr.md
  bertytech/content/blog/countering-censorship/index.fr.md
  bertytech/content/blog/future-of-berty/index.fr.md
  bertytech/content/blog/future-of-berty/index.md
  bertytech/content/blog/ipfs-camp/index.fr.md
  bertytech/content/blog/post-fosdem-2020/index.fr.md
  bertytech/content/blog/privacy-security-safety/index.fr.md
  bertytech/content/blog/privacy-social-network/index.fr.md
  bertytech/content/blog/stop-spying-on-me/index.fr.md
  bertytech/content/blog/top-privacy-leak-2018/index.fr.md
  bertytech/content/compare-table-apps/berty.fr.md
  bertytech/content/compare-table-apps/facebook.fr.md
  bertytech/content/compare-table-apps/firechat.fr.md
  bertytech/content/compare-table-apps/imessage.fr.md
  bertytech/content/compare-table-apps/jami.fr.md
  bertytech/content/compare-table-apps/matrix.fr.md
  bertytech/content/compare-table-apps/olvid.fr.md
  bertytech/content/compare-table-apps/session.fr.md
  bertytech/content/compare-table-apps/signal.fr.md
  bertytech/content/compare-table-apps/skred.fr.md
  bertytech/content/compare-table-apps/skuttlebut.fr.md
  bertytech/content/compare-table-apps/telegram.fr.md
  bertytech/content/compare-table-apps/threema.fr.md
  bertytech/content/compare-table-apps/wechat.fr.md
  bertytech/content/compare-table-apps/whatsapp.fr.md
  bertytech/content/docs/protocol/index.fr.md
  bertytech/content/hello.fr.md
  bertytech/content/id.fr.md
  bertytech/content/newsletter/news-12/index.fr.md
  bertytech/content/newsletter/news-13/index.fr.md
  bertytech/content/press/index.fr.md
  bertytech/content/terms/index.fr.md
Labels: enhancement, 🔍 Ready for Review

#194 fix: New Crowdin updates
  bertytech/content/blog/future-of-berty/index.fr.md
  bertytech/content/blog/metadata-mobile-messaging/index.fr.md
  bertytech/content/blog/nothing-to-hide/index.fr.md
  bertytech/content/blog/paris-p2p/index.fr.md
  bertytech/content/blog/privacy-social-network/index.fr.md
  bertytech/content/blog/stop-spying-on-me/index.fr.md
  bertytech/content/blog/top-privacy-leak-2018/index.fr.md
  bertytech/content/docs/protocol/index.fr.md
Labels: bug, 🔍 Ready for Review

#196 feat: create news-49
  bertytech/content/newsletter/news-49/index.md
Labels: enhancement

#198 Change contribute translations to crowdin url
  bertytech/config.yaml
  bertytech/layouts/shortcodes/display_section_contribute.html
Labels: ✅ Approved

#197 New Crowdin updates
  bertytech/content/blog/closed-beta-berty/index.fr.md
  bertytech/content/newsletter/news-49/index.fr.md
Labels: ✅ Approved

#199 fix: new Crowdin updates
  bertytech/content/blog/berty-at-p2p-festival/index.fr.md
  bertytech/content/blog/smartphone-surveillance/index.fr.md
Labels: bug, ✅ Approved

#200 New Crowdin updates
  bertytech/content/blog/berty-at-p2p-festival/index.fr.md
  bertytech/content/blog/nothing-to-hide/index.fr.md
  bertytech/content/blog/privacy-social-network/index.fr.md
Labels: ✅ Approved

#201 feat: support all QR codes
  bertytech/assets/css/style.scss
  bertytech/assets/js/main.js
  bertytech/layouts/shortcodes/display_section_id.md
Labels: enhancement, 🔍 Ready for Review

#202 feat: create blog post about how to encrypt your life
  bertytech/content/blog/encrypt-your-life/2020-11-23-Berty-Blogpost-How_To_Encrypt_Your_Life_In_10_Min-2.png
  bertytech/content/blog/encrypt-your-life/index.md
Labels: enhancement, 🔍 Ready for Review

#205 Dev/pierre/nl50
  bertytech/content/newsletter/news-50/index.md
Labels: 🔍 Ready for Review
