Repository berty/www.berty.tech, pull requests merged in 2020-07, with the labels that each got.

#106 feat(blog): create dao blogpost
  bertytech/assets/img/avatar_philh.png
  bertytech/content/blog/dao-berty-1/dao-berty.png
  bertytech/content/blog/dao-berty-1/index.md
  bertytech/data/authors.yml
  bertytech/layouts/partials/post_card.html
  bertytech/layouts/partials/post_footer.html
Labels: 🔍 Ready for Review

#108 feat(blog): create gomobile-ipfs blogpost
  bertytech/assets/img/avatar_gfanton.png
  bertytech/content/blog/gomobile-ipfs/gomobile-ipfs.jpg
  bertytech/content/blog/gomobile-ipfs/index.md
  bertytech/data/authors.yml
Labels: 🔍 Ready for Review

#107 chore(blog):modify covers
  bertytech/content/blog/nothing-to-hide/index.md
  bertytech/content/blog/nothing-to-hide/nothing-to-hide.jpg
  bertytech/content/blog/privacy-security-safety/index.md
  bertytech/content/blog/privacy-security-safety/privacy-security-safety.jpg
Labels: 🔍 Ready for Review

#111 chore(blog): changing cover
  bertytech/content/blog/digital_signature/Digital-Signature.jpg
  bertytech/content/blog/digital_signature/index.md
Labels: chore, ✅ Approved

#113 fix: minor typo fix
  bertytech/content/challenges/2-technical-challenges/index.md
Labels: bug, ✅ Approved

#114 feat(blog): create watching #2
  bertytech/content/blog/watching-hongkong/Watching-Hong-Kong-updates.png
  bertytech/content/blog/watching-hongkong/index.md
Labels: enhancement, ✅ Approved

#89 Add Discourse comments
  bertytech/config.yaml
  bertytech/layouts/blog/single.html
  bertytech/layouts/newsletter/single.html
  bertytech/layouts/partials/discourse_comments.html
  bertytech/layouts/partials/head.html
Labels: 🔍 Ready for Review

#115 feat: create news-40
  bertytech/content/newsletter/news-40/index.md
Labels: enhancement, 🔍 Ready for Review

#116 fix: remove trailing slash from discourse domain
  bertytech/config.yaml
Labels: bug, 🔍 Ready for Review

#119 chore(blog): fix covers
  bertytech/content/blog/national-security-privacy/index.md
  bertytech/content/blog/national-security-privacy/national-defense.jpg
  bertytech/content/blog/privacy-social-network/index.md
  bertytech/content/blog/privacy-social-network/privacy-social-media.jpg
  bertytech/content/blog/privacy-social-network/social-media.jpg
Labels: chore, ✅ Approved

#120 chore: fix covers
  bertytech/content/blog/E2E-encryption/E2EE-encryption.jpg
  bertytech/content/blog/E2E-encryption/index.md
  bertytech/content/blog/how-vpn-phone/index.md
  bertytech/content/blog/how-vpn-phone/vpn-phone.jpg
Labels: chore, ✅ Approved

#121 fix: signal messenger comparison - maybe was confused with Status
  bertytech/content/compare-table-apps/signal.md
Labels: bug, ✅ Approved

#122 feat: create zooma blogpost about reasons to berty
  bertytech/content/blog/reasons-to-berty/index.md
  bertytech/content/blog/reasons-to-berty/reasons-to-berty.jpg
Labels: enhancement, ✅ Approved

#123 feat: create news41
  bertytech/content/newsletter/news-41/index.md
Labels: enhancement, ✅ Approved

#124 feat: create blog about future of berty
  bertytech/content/blog/future-of-berty/future-berty.jpg
  bertytech/content/blog/future-of-berty/index.md
Labels: enhancement, ✅ Approved

#125 docs: update matrix.md
  bertytech/content/compare-table-apps/matrix.md
Labels: documentation, ✅ Approved

#128 chore: add session.app
  bertytech/content/compare-table-apps/session.md
Labels: chore, ✅ Approved

#129 chore: fixing last cover
  bertytech/content/blog/history-cryptography/2020-07-29-Berty-Blogpost-History_of_cryptography.jpg
  bertytech/content/blog/history-cryptography/index.md
Labels: chore, ✅ Approved, 🔍 Ready for Review

#126 Update FAQ
  bertytech/content/faq/10-Will the app hide ip addresses and metadata?/index.md
  bertytech/content/faq/11-What's the encryption protocol used in Berty?/index.md
  bertytech/content/faq/12-Will Berty be free?/index.md
  bertytech/content/faq/13-Will Berty have features such as self-destructing messages and BOR?/index.md
  bertytech/content/faq/14-Will it have file sharing, voice-& video chat?/index.md
Labels: ✅ Approved
