Repository berty/www.berty.tech, pull requests merged in 2020-06, with the labels that each got.

#74 feat: update protocol with new version
  .gitignore
  AUTHORS
  bertytech/assets/css/style.scss
  bertytech/content/docs/protocol/B1onw7wdI.png
  bertytech/content/docs/protocol/B1qIgVw_8.png
  bertytech/content/docs/protocol/BJAQwQP_I.png
  bertytech/content/docs/protocol/BJWLZR6vU.png
  bertytech/content/docs/protocol/BkFkKBDOU.png
  bertytech/content/docs/protocol/BymgCaaDI.png
  bertytech/content/docs/protocol/H1jJ6fvdI.png
  bertytech/content/docs/protocol/HJ9wKg0PL.png
  bertytech/content/docs/protocol/HkAFBapv8.png
  bertytech/content/docs/protocol/Hkn4kg0v8.png
  bertytech/content/docs/protocol/Hks1bEvu8.png
  bertytech/content/docs/protocol/Hy-d6h6wL.png
  bertytech/content/docs/protocol/HyEDRMvO8.png
  bertytech/content/docs/protocol/SJ6dgzaiU.png
  bertytech/content/docs/protocol/SkWZnyPOU.png
  bertytech/content/docs/protocol/SkXjmJRvL.png
  bertytech/content/docs/protocol/SklLFmD_I.png
  bertytech/content/docs/protocol/index.md
  bertytech/content/docs/protocol/rJP2m-vO8.png
  bertytech/content/docs/protocol/rkI4GWD_8.png
  bertytech/content/docs/protocol/rkYDSaaDI.png
  bertytech/content/docs/protocol/ry6qXApPU.png
  bertytech/content/docs/protocol/ryrmDTpw8.png
  bertytech/layouts/_default/_markup/render-image.html
Labels: ✅ Approved

#75 feat: switch from Berty Chat to Berty Messenger
  bertytech/content/blog/bluetooth-low-energy/index.md
  bertytech/content/challenges/2-technical-challenges/index.md
  bertytech/content/docs/berty/index.md
  bertytech/content/features/index.md
Labels: 🔍 Ready for Review

#77 chore: Add padding to code blocks
  bertytech/assets/css/style.scss
  bertytech/postcss.config.js
Labels: ✅ Approved

#78 feat: add berty.tech/ipfs-webui-packed
  bertytech/go-get.csv
Labels: 🔍 Ready for Review

#79 chore:resize gif
  bertytech/content/blog/bluetooth-low-energy/B1_hcXoDL.gif
  bertytech/content/blog/bluetooth-low-energy/giphy2.gif
  bertytech/content/blog/bluetooth-low-energy/rkbQMNjvI.gif
Labels: 🔍 Ready for Review

#80 chore: update index.md
  bertytech/content/docs/community/index.md
Labels: ✅ Approved

#81 chore: update index.md
  bertytech/content/docs/community/index.md
Labels: 🔍 Ready for Review

#63 Change features page layout
  bertytech/assets/css/style.scss
  bertytech/content/features/1-BLE.png
  bertytech/content/features/2-any-device.png
  bertytech/content/features/3-share-details.png
  bertytech/content/features/4-No_servers.png
  bertytech/content/features/5-fully-distributed.png
  bertytech/content/features/noface-noname.png
  bertytech/content/features/qrcode.png
  bertytech/content/features/secure-encryption.png
  bertytech/layouts/shortcodes/display_section_features.html
Labels: 🔍 Ready for Review

#83 added the mention of "no cloud" and peer-to-peer
  bertytech/layouts/shortcodes/display_section_features.html
Labels: ✅ Approved

#82 Remove sitemap submission on postbuild
  bertytech/netlify.toml
  bertytech/package-lock.json
  bertytech/package.json
  bertytech/post-build.sh
Labels: ✅ Approved

#86 feat:create nl38
  bertytech/content/newsletter/news-38/index.md
Labels: 🔍 Ready for Review

#85 Initial comparison table
  bertytech/assets/css/style.scss
  bertytech/content/compare-table-apps/berty.md
  bertytech/content/compare-table-apps/facebook.md
  bertytech/content/compare-table-apps/firechat.md
  bertytech/content/compare-table-apps/imessage.md
  bertytech/content/compare-table-apps/index.md
  bertytech/content/compare-table-apps/jami.md
  bertytech/content/compare-table-apps/matrix.md
  bertytech/content/compare-table-apps/olvid.md
  bertytech/content/compare-table-apps/signal.md
  bertytech/content/compare-table-apps/skred.md
  bertytech/content/compare-table-apps/skuttlebut.md
  bertytech/content/compare-table-apps/telegram.md
  bertytech/content/compare-table-apps/wechat.md
  bertytech/content/compare-table-apps/whatsapp.md
  bertytech/content/faq/1-advantages/index.md
  bertytech/layouts/faq/list.html
  bertytech/layouts/partials/compare-messenger-apps.html
  bertytech/layouts/shortcodes/compare-messenger-apps.html
  bertytech/postcss.config.js
Labels: 🔍 Ready for Review

#84 Update images on features page
  bertytech/content/features/1-BLE.png
  bertytech/content/features/2-any-device.png
  bertytech/content/features/3-share-details.png
  bertytech/content/features/4-No_servers.png
  bertytech/content/features/5-fully-distributed.png
  bertytech/content/features/available-on-devices.png
  bertytech/content/features/fully_distributed.png
  bertytech/content/features/no_servers.png
  bertytech/content/features/share-your-details.png
  bertytech/content/features/using_BLE.png
  bertytech/layouts/shortcodes/display_section_features.html
Labels: ✅ Approved

#88 feat(blog):create blogpost stop spying
  bertytech/content/blog/stop-spying-on-me/index.md
  bertytech/content/blog/stop-spying-on-me/stop-spying.jpg
Labels: ✅ Approved

#91 fix: use absolute path for links on 404 page
  bertytech/layouts/partials/footer.html
  bertytech/layouts/partials/navbar.html
Labels: ✅ Approved, 🔍 Ready for Review

#92 feat: add blockquote styling
  bertytech/assets/css/style.scss
Labels: ✅ Approved

#95 Make first column compare table fixed
  bertytech/assets/css/style.scss
  bertytech/layouts/partials/compare-messenger-apps.html
Labels: ✅ Approved

#96 feat(blog): create blog post about how berty works
  bertytech/content/blog/how-berty-works-ipfs/HBW1.jpg
  bertytech/content/blog/how-berty-works-ipfs/index.md
Labels: ✅ Approved

#98 fix: workaround fix for amp-script classList
  bertytech/assets/js/amp-faq.js
  bertytech/assets/js/amp-navbar.js
Labels: ✅ Approved

#99 Upgrade hugo version 0.73.0
  bertytech/netlify.toml
Labels: ✅ Approved

#100 Add FAQ anchors
  bertytech/assets/css/style.scss
  bertytech/assets/js/amp-faq.js
  bertytech/layouts/partials/block_faq.html
Labels: ✅ Approved, 🔍 Ready for Review

#101 chore: revert AMP script classList workaround
  bertytech/assets/js/amp-faq.js
  bertytech/assets/js/amp-navbar.js
Labels: ✅ Approved

#102 feat: create news39
  bertytech/content/newsletter/news-39/index.md
Labels: 🔍 Ready for Review

#105 Remove matrix
  bertytech/layouts/partials/nav_social.html
  bertytech/layouts/shortcodes/display_section_social.html
Labels: ✅ Approved
