Repository berty/www.berty.tech, pull requests merged in 2021-07, with the labels that each got.

#282 feat: rm airtable form link for preview
  bertytech/content/faq/8-how can I get Berty/index.md
Labels: enhancement, 🔍 Ready for Review

#284 Fix links
  bertytech/content/docs/berty/index.md
Labels: ✅ Approved

#283 Update index.md
  bertytech/content/docs/gomobile-ipfs/index.md
Labels: ✅ Approved, 🔍 Ready for Review

#286 fix: link to the right file
  bertytech/content/docs/berty/index.md
Labels: bug, 🔍 Ready for Review

#289 feat: create NL62
  bertytech/content/newsletter/news-62/index.md
Labels: enhancement, ✅ Approved

#288 Update briar.md
  bertytech/content/compare-table-apps/briar.md
Labels: 🔍 Ready for Review

#290 chore: fix content
  bertytech/content/blog/create-strong-password/index.md
Labels: chore, ✅ Approved

#292 small typo fix on section_value.html
  bertytech/layouts/partials/section_values.html
Labels: 🔍 Ready for Review

#291 Update and rename skuttlebut.md to scuttlebut.md
  bertytech/content/compare-table-apps/scuttlebut.md
Labels: ⚠️ Changes requested

#294 feat: create nl63
  bertytech/content/newsletter/news-63/index.md
Labels: enhancement

#295 Create index.md
  bertytech/content/newsletter/news-63/index.md
Labels: 🔍 Ready for Review
