Repository berty/www.berty.tech, pull requests merged in 2021-05, with the labels that each got.

#267 chore: add newsletter 58
  bertytech/content/newsletter/news-58/index.md
Labels: chore

#273 feat: create nl59
  bertytech/content/newsletter/news-59/index.md
Labels: enhancement

#274 fix: fix link
  bertytech/content/newsletter/news-59/index.md
Labels: bug
