Repository berty/www.berty.tech, pull requests merged in 2021-12, with the labels that each got.

#309 feat: create NL69
  bertytech/content/newsletter/news-69/index.md
Labels: enhancement, ✅ Approved

#311 chore: berty.tech/discord redirect
  bertytech/layouts/partials/_redirects
Labels: 🔍 Ready for Review, chore

#312 chore: updated privacy policy
  bertytech/content/privacy-policy/index.md
Labels: 🔍 Ready for Review, chore

#313 feat: create nl70
  bertytech/content/newsletter/news-70/index.md
Labels: enhancement, 🔍 Ready for Review
