Repository berty/www.berty.tech, pull requests merged in 2021-06, with the labels that each got.

#278 feat: create nl60
  bertytech/content/newsletter/news-60/index.md
Labels: enhancement

#279 fix: broken link
  bertytech/content/newsletter/news-60/index.md
Labels: bug

#280 chore: add temporary privacy policy for alpha
  bertytech/content/privacy-policy/index.md
Labels: chore, 🔍 Ready for Review

#281 feat: news-61
  bertytech/content/newsletter/news-61/index.md
Labels: enhancement, 🔍 Ready for Review
